### ISSUE TITLE
Other Error: name 'path' is not defined

### ISSUE THREAD

**Issue by wergio** [kuchel77/diskspace#3]
I get this error (HASSIO in docker in Rpi4)
```
WARNING (SyncWorker_14) [custom_components.diskspace.sensor] Other Error: name 'path' is not defined
```
my conf:
```
sensor:
  - platform: diskspace
    name: SD Card
    path: "/"
    unit_of_measure: "GB"
```
