### ISSUE TITLE
No setup function defined.

### ISSUE THREAD

**Issue by pdivers** [kuchel77/diskspace#4]
I keep seeing this in my notifications:
"The following integrations and platforms could not be set up:
diskspace
Please check your config."
and this in my log:
2020-03-01 00:15:53 ERROR (MainThread) [homeassistant.setup] Setup failed for diskspace: No setup function defined.

Otherwise it appears to be working...

**Comment by kuchel77** [comment]
What version are you using? What does your config look like?

**Comment by pdivers** [comment]
diskspace: Installed: v0.7
HA:  105.2

configuration.yaml contains
diskspace:

**Comment by kuchel77** [comment]
In your configuration.yaml file, you need to have it as part of your sensor: section.

```yaml
sensor:
  - platform: diskspace
    name: Main Disk
    path: "/"
    unit_of_measure: "GB"
```

Is the main one I have at the moment on my setup. I have a few other sensors as part of this as well, so my sensor: config looks more like 

```yaml
sensor:
  - platform: template
    sensors:
      washing_machine_status:
        value_template: "{{ states.input_select.washing_machine_status.state}}"
        friendly_name: "Washing Machine Status"
      dishwasher_status:
        value_template: "{{ states.input_select.dishwasher_status.state}}"
        friendly_name: "Dishwasher Status"
      rubbish_bin_status:
        value_template: "{{ states.input_select.rubbish_bin_status.state}}"
        friendly_name: "Rubbish Bin Status"
      recycling_bin_status:
        value_template: "{{ states.input_select.recycling_bin_status.state}}"
        friendly_name: "Recycling Bin Status"
  - platform: sonarr_upcoming_media
    host: 192.168.0.200
    port: 18989
  - platform: radarr_upcoming_media
    host: 192.168.0.200
    port: 7878
  - platform: plex_recently_added
    host: 192.168.0.200
    port: 32400
  - platform: diskspace
    name: Main Disk
    path: "/"
    unit_of_measure: "GB"
```

Rather than just a diskspace: in your configuration.yaml section. *Note, I have deleted the keys and a few other sections from my sensors*

**Comment by pdivers** [comment]
oh yes, sorry, i have that in a package as follows:

```
homeassistant:
  customize:
    sensor.disk_space_main_disk:
      icon: mdi:harddisk
    sensor.home_assistant_uptime:
      icon: mdi:clock-start

automation:
- alias: Low Disk Space
  description: "Notify me of low disk space"
  trigger:
    - platform: template
      value_template: "{% if state_attr('sensor.disk_space_main_disk', 'percentage_free') < 30 %}true{% endif %}"
  condition: []
  action:
  - service: notify.sms
    data:
      message: Main disk is almost full
      target: !secret sid_phone
 
sensor:
- platform: uptime
  name: uptime_min
  unit_of_measurement: minutes

- platform: diskspace
  name: Main Disk
  path: "/"
  unit_of_measure: "GB"

```
