### ISSUE TITLE
How to check mounted disk space

### ISSUE THREAD

**Issue by rzechu** [kuchel77/diskspace#6]
I have seen there's closed topic from february but looks like it isn't solved.

```
pi@rpi4:~ $ df
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/root      240129924 228607656   1734336 100% /
devtmpfs         1736208         0   1736208   0% /dev
tmpfs            1868304         0   1868304   0% /dev/shm
tmpfs            1868304     57652   1810652   4% /run
tmpfs               5120         4      5116   1% /run/lock
tmpfs            1868304         0   1868304   0% /sys/fs/cgroup
/dev/sda1         258095     55053    203042  22% /boot
/dev/sdb1      488383484 216009236 272374248  45% /mnt/hdd500
tmpfs             373660         0    373660   0% /run/user/1000

```

```
sensor:
  - platform: diskspace
    name: Main Disk
    path: "/"
    unit_of_measure: "GB"
    
  - platform: diskspace
    name: Hdd500 External
    path: "/dev/sdb1"
    unit_of_measure: "GB"
```

1st one works perfectly. But 2nd doesnt. 
Total 0
Used 0
Free 0
Percentage free 100

using MB
Total 67
Used 0
Free 67
Percentage free 100

I Have tried /mnt/hdd500 too but it doesnt works at all
